In [2]:
import numpy as np

# Q1

In [3]:
my_array = np.array([1,2,3])
my_list = my_array.tolist()
my_list




[1, 2, 3]

# Q2

### Method 1

In [4]:
# creating a 3X3 Numpy matrix
my_array = np.array([[10, 20, 130,2],[1, 30, 3,3],[11, 20, 40,4],[11, 20, 50,6]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(my_array)
  
# calculating the Trace of a matrix ( The sum of the diagonal elements of a given array.)
s = np.trace(my_array)
  
print("\n la somme de diagonale:", s)

Numpy Matrix is:
[[ 10  20 130   2]
 [  1  30   3   3]
 [ 11  20  40   4]
 [ 11  20  50   6]]

 la somme de diagonale: 86


### Method 2 

In [5]:
# creating a 3X3 Numpy matrix
my_array = np.array([[10, 20, 130,2],[1, 30, 3,3],[11, 20, 40,4],[11, 20, 50,6]])
elem_diag = my_array.diagonal()
s=0
for i in range(len(elem_diag)):
    s = s + elem_diag[i]
print("\n la somme de diagonale:", s)


 la somme de diagonale: 86


# Q3

In [6]:
t = np.array([[10, 20, 130],[1, 30, 3]])
x = 10
for i in range(t.shape[0]):
     for j in range(t.shape[1]):
            if t[i][j] > x:
                print("le nombre suivant est supérieur à 10 : ",t[i][j])


le nombre suivant est supérieur à 10 :  20
le nombre suivant est supérieur à 10 :  130
le nombre suivant est supérieur à 10 :  30


# Q4

In [7]:
A = np.array([[10, 20, 130],[1, 30, 3],[11, 20, 40]])
B = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
C = A+B
print(C)

[[ 11  22 133]
 [  5  35   9]
 [ 18  28  49]]


# Q5

In [8]:
arr = np.array([[3, 3, 3], [1, 2, 3]])
moy = np.mean(arr, axis=1)#axis=1 => ligne #axis=0 => colonne 
moy

array([3., 2.])